before_install:
  - gem install bundler

rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.1

script: rake spec

gemfile:
  - gemfiles/rails-4-2-stable.gemfile
  - gemfiles/rails-4-1-stable.gemfile
  - gemfiles/rails-3-2-stable.gemfile
